branch-defaults:
  master:
    environment: my-django-app-env
    group_suffix: null
global:
  application_name: my-django-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
